import type { AnalysisHistoryItem, MarketAnalysisResponse } from './types'

export const marketAnalysisReports: MarketAnalysisResponse[] = [
  {
    schema_version: 'market-analysis.v1',
    market: {
      id: 'habit-tracking-apps',
      name: 'Habit Tracking Apps',
      definition: 'Consumer apps that help individuals build and maintain recurring habits.',
      scope: {
        geography: ['Global'],
        platforms: ['iOS', 'Android', 'Web'],
        customer_type: 'B2C',
        included: ['Habit tracking', 'Streaks', 'Reminders', 'Accountability'],
        excluded: ['Clinical treatment', 'Enterprise wellness', 'Project management'],
      },
    },
    report: {
      id: 'report_habit_2026_09',
      version: 3,
      status: 'completed',
      generated_at: '2026-09-06T08:30:00Z',
      data_period: 'Jan 2024 - Aug 2026',
      overall_confidence: 72,
      freshness: 'current',
      warnings: [],
    },
    overview: {
      verdict: {
        status: 'selectively_attractive',
        summary: 'Demand remains strong, but the general-purpose segment is mature and highly commoditized.',
        strengths: ['Persistent consumer demand', 'Large mobile audience', 'Established willingness to pay'],
        constraints: ['High category churn', 'Low switching costs', 'Feature saturation'],
      },
      scorecard: {
        demand: 81,
        market_size: 68,
        momentum: 64,
        commercial_quality: 59,
        accessibility: 61,
        competitive_headroom: 35,
      },
      market_size: {
        metrics: [
          {
            id: 'annual_revenue',
            label: 'Estimated annual revenue',
            range: { min: 80000000, max: 110000000 },
            unit: 'USD',
            period: '2025',
            change: { value: 18, unit: 'percent', period: 'YoY' },
            evidence_class: 'derived',
            confidence: 68,
            source_ids: ['src_01', 'src_02'],
            methodology: 'Aggregated estimates for 25 tracked products',
          },
          {
            id: 'annual_downloads',
            label: 'Annual downloads',
            value: 42000000,
            unit: 'downloads',
            period: '2025',
            change: { value: 7, unit: 'percent', period: 'YoY' },
            evidence_class: 'estimated',
            confidence: 74,
            source_ids: ['src_02'],
          },
          {
            id: 'search_interest',
            label: 'Search demand index',
            value: 67,
            unit: 'index',
            period: '2026 YTD',
            change: { value: 16, unit: 'percent', period: 'YoY' },
            evidence_class: 'proxy',
            confidence: 76,
            source_ids: ['src_03'],
          },
        ],
      },
      momentum: {
        direction: 'growing',
        strength: 'moderate',
        summary: 'Revenue and search demand are increasing faster than downloads.',
        signals: [
          { label: 'Consumer spending', change: 18, unit: 'percent', period: 'YoY', source_ids: ['src_01'] },
          { label: 'Downloads', change: 7, unit: 'percent', period: 'YoY', source_ids: ['src_02'] },
          { label: 'Search interest', change: 16, unit: 'percent', period: 'YoY', source_ids: ['src_03'] },
        ],
        series: [
          { period: '2024', revenue: 72000000, downloads: 37000000, search_index: 52 },
          { period: '2025', revenue: 95000000, downloads: 42000000, search_index: 61 },
          { period: '2026 YTD', revenue: null, downloads: 31000000, search_index: 67 },
        ],
      },
      customer_segments: [
        {
          id: 'productivity-users',
          name: 'Productivity-focused professionals',
          jobs: ['Maintain routines', 'Track consistency', 'Review progress'],
          pain_points: ['Manual input fatigue', 'Rigid streak systems'],
          willingness_to_pay: 'moderate',
          confidence: 78,
          source_ids: ['src_04'],
        },
        {
          id: 'adhd-users',
          name: 'ADHD and neurodivergent users',
          jobs: ['Recover after missed days', 'Reduce cognitive load', 'Build flexible routines'],
          pain_points: ['Punitive streak loss', 'Overwhelming setup', 'Notification fatigue'],
          willingness_to_pay: 'moderate',
          confidence: 74,
          source_ids: ['src_04', 'src_06'],
        },
        {
          id: 'wellness-users',
          name: 'Wellness-oriented consumers',
          jobs: ['Connect habits to wellbeing', 'See long-term patterns'],
          pain_points: ['Fragmented health data', 'Weak actionable insight'],
          willingness_to_pay: 'low',
          confidence: 66,
          source_ids: ['src_04'],
        },
      ],
      commercial_dynamics: {
        dominant_model: 'Freemium subscription',
        typical_annual_price: { min: 20, max: 60, unit: 'USD' },
        willingness_to_pay: 'moderate',
        retention_pressure: 'high',
        summary: 'Subscription is validated, but habit abandonment limits customer lifetime value.',
        source_ids: ['src_01', 'src_04'],
      },
      market_accessibility: {
        level: 'moderate',
        channels: ['App Store search', 'SEO', 'Productivity communities', 'Creator content'],
        barriers: ['Crowded app-store keywords', 'Strong incumbent reviews', 'Low switching cost'],
        summary: 'The audience is reachable, but organic discovery is competitive.',
        confidence: 70,
        source_ids: ['src_03', 'src_04'],
      },
      risks: [
        {
          id: 'risk_01',
          category: 'Retention',
          title: 'High category churn',
          probability: 'high',
          impact: 'high',
          summary: 'Users frequently abandon tracking after initial motivation declines.',
          source_ids: ['src_04'],
        },
        {
          id: 'risk_02',
          category: 'Competition',
          title: 'Feature commoditization',
          probability: 'high',
          impact: 'moderate',
          summary: 'Reminders, streaks, widgets, and basic analytics are widely available.',
          source_ids: ['src_05'],
        },
        {
          id: 'risk_03',
          category: 'Distribution',
          title: 'Expensive mobile discovery',
          probability: 'moderate',
          impact: 'high',
          summary: 'Generic category keywords are dominated by established products.',
          source_ids: ['src_03', 'src_05'],
        },
      ],
      opportunity_gaps: [
        {
          id: 'gap_01',
          segment: 'ADHD and neurodivergent users',
          unmet_need: 'Flexible habit recovery without streak-loss punishment.',
          competitor_coverage: 'low',
          demand_strength: 'high',
          commercial_signal: 'moderate',
          confidence: 74,
          source_ids: ['src_04', 'src_06'],
        },
        {
          id: 'gap_02',
          segment: 'Small accountability groups',
          unmet_need: 'Private social accountability without a public community feed.',
          competitor_coverage: 'moderate',
          demand_strength: 'moderate',
          commercial_signal: 'moderate',
          confidence: 69,
          source_ids: ['src_04', 'src_06'],
        },
        {
          id: 'gap_03',
          segment: 'Wellness-oriented consumers',
          unmet_need: 'Explain how routines correlate with sleep, energy, and mood.',
          competitor_coverage: 'low',
          demand_strength: 'moderate',
          commercial_signal: 'low',
          confidence: 63,
          source_ids: ['src_04', 'src_05'],
        },
      ],
    },
    competitors: {
      summary: {
        competition_level: 'high',
        market_structure: 'fragmented',
        tracked_products: 25,
        top_10_revenue_concentration: 64,
        feature_saturation: 'high',
        switching_cost: 'low',
        source_ids: ['src_01', 'src_02', 'src_05'],
      },
      items: [
        {
          id: 'habitica',
          name: 'Habitica',
          type: 'direct',
          positioning: 'Gamified habits and task management',
          platforms: ['iOS', 'Android', 'Web'],
          pricing: { model: 'Freemium', annual_price: 47.99, currency: 'USD' },
          strengths: ['Distinctive positioning', 'Community mechanics'],
          weaknesses: ['Complex interface', 'Niche visual style'],
          confidence: 86,
          source_ids: ['src_07', 'src_08'],
        },
        {
          id: 'streaks',
          name: 'Streaks',
          type: 'direct',
          positioning: 'Focused habit tracking for Apple users',
          platforms: ['iOS', 'macOS', 'watchOS'],
          pricing: { model: 'One-time purchase', annual_price: null, currency: 'USD' },
          strengths: ['Focused experience', 'Deep Apple integration'],
          weaknesses: ['Apple-only reach', 'Rigid streak model'],
          confidence: 82,
          source_ids: ['src_07', 'src_08'],
        },
        {
          id: 'productive',
          name: 'Productive',
          type: 'direct',
          positioning: 'Guided routines and habit programs',
          platforms: ['iOS', 'Android'],
          pricing: { model: 'Subscription', annual_price: 39.99, currency: 'USD' },
          strengths: ['Polished onboarding', 'Broad routine library'],
          weaknesses: ['Aggressive paywall', 'Generic recommendations'],
          confidence: 79,
          source_ids: ['src_07', 'src_08'],
        },
      ],
    },
    evidence: [
      ['src_01', 'Consumer spending estimate', 'Mobile intelligence provider', 'estimated'],
      ['src_02', 'Category download estimate', 'Mobile intelligence provider', 'estimated'],
      ['src_03', 'Habit tracking search interest', 'Search provider', 'proxy'],
      ['src_04', 'Customer review and pain-point analysis', 'Research dataset', 'derived'],
      ['src_05', 'Habit tracker feature landscape', 'Research dataset', 'derived'],
      ['src_06', 'Underserved user segment discussions', 'Community dataset', 'proxy'],
      ['src_07', 'Competitor product and pricing pages', 'Tracked competitors', 'reported'],
      ['src_08', 'Competitor review summary', 'Review platform', 'derived'],
    ].map(([id, title, publisher, evidence_class]) => ({
      id,
      title,
      publisher,
      url: `https://example.com/${id}`,
      published_at: '2026-08-20',
      retrieved_at: '2026-09-06T08:15:00Z',
      evidence_class: evidence_class as 'reported' | 'estimated' | 'derived' | 'proxy',
    })),
  },
]

export const defaultMarketId = marketAnalysisReports[0]!.market.id

export const analysisHistory: AnalysisHistoryItem[] = [
  {
    id: 'report_habit_2026_09',
    market_id: 'habit-tracking-apps',
    type: 'Market analysis',
    status: 'completed',
    version: 3,
    source_count: 8,
    saved_at: 'Sep 6, 2026 at 15:30',
  },
  {
    id: 'report_habit_2026_08',
    market_id: 'habit-tracking-apps',
    type: 'Competitor update',
    status: 'completed',
    version: 2,
    source_count: 6,
    saved_at: 'Aug 28, 2026 at 09:16',
  },
]
