"""Versioned contracts shared across independently deployable services."""

from distributed_agent_contracts.analyst import AnalysisRequest, AnalysisResponse
from distributed_agent_contracts.common import (
    Citation,
    CompetitiveSignal,
    ContractError,
    ContractStatus,
    ErrorCode,
    Finding,
    RequestMetadata,
    Source,
    copy_request_metadata,
    render_citation_links,
)
from distributed_agent_contracts.deadlines import (
    ModelTimeoutBudget,
    model_timeout_budget,
    remaining_seconds,
)
from distributed_agent_contracts.market_analysis import (
    AppendConversationMessageRequest,
    AppMarketResearchInput,
    AppMarketResearchOutput,
    ConversationMessage,
    ConversationReviewContext,
    EvidenceFact,
    MarketAnalysisResponse,
    MarketReportDraft,
    MarketResearchBudgets,
    MarketScope,
    PersistMarketReportDraftRequest,
    PublishApprovedMarketReportRequest,
    PublishMarketReportRequest,
    PublishMarketReportResponse,
    ReportReviewActionInput,
    ReportReviewDecision,
    ReportReviewEvent,
    ResearchPublication,
    SourceSnapshot,
)
from distributed_agent_contracts.market_analyst import (
    MarketAnalystInput,
    MarketAnalystOutput,
    MarketAnalystRemoteState,
)
from distributed_agent_contracts.orchestrator import WorkflowRequest, WorkflowResponse
from distributed_agent_contracts.writer import ExecutiveBrief, WriterRequest, WriterResponse

__all__ = [
    "AnalysisRequest",
    "AnalysisResponse",
    "AppMarketResearchInput",
    "AppMarketResearchOutput",
    "AppendConversationMessageRequest",
    "Citation",
    "CompetitiveSignal",
    "ContractError",
    "ContractStatus",
    "ConversationMessage",
    "ConversationReviewContext",
    "ErrorCode",
    "EvidenceFact",
    "ExecutiveBrief",
    "Finding",
    "MarketAnalysisResponse",
    "MarketAnalystInput",
    "MarketAnalystOutput",
    "MarketAnalystRemoteState",
    "MarketReportDraft",
    "MarketResearchBudgets",
    "MarketScope",
    "ModelTimeoutBudget",
    "PersistMarketReportDraftRequest",
    "PublishApprovedMarketReportRequest",
    "PublishMarketReportRequest",
    "PublishMarketReportResponse",
    "ReportReviewActionInput",
    "ReportReviewDecision",
    "ReportReviewEvent",
    "RequestMetadata",
    "ResearchPublication",
    "Source",
    "SourceSnapshot",
    "WorkflowRequest",
    "WorkflowResponse",
    "WriterRequest",
    "WriterResponse",
    "copy_request_metadata",
    "model_timeout_budget",
    "remaining_seconds",
    "render_citation_links",
]
