# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from distributed_agent_contracts.competitor.v1 import competitor_pb2 as distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in distributed_agent_contracts/competitor/v1/competitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompetitorAnalystStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeCompetitors = channel.unary_unary(
                '/distributed_agents.competitor.v1.CompetitorAnalyst/AnalyzeCompetitors',
                request_serializer=distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisRequest.SerializeToString,
                response_deserializer=distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisResponse.FromString,
                _registered_method=True)


class CompetitorAnalystServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeCompetitors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompetitorAnalystServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeCompetitors': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeCompetitors,
                    request_deserializer=distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisRequest.FromString,
                    response_serializer=distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_agents.competitor.v1.CompetitorAnalyst', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_agents.competitor.v1.CompetitorAnalyst', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompetitorAnalyst:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeCompetitors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_agents.competitor.v1.CompetitorAnalyst/AnalyzeCompetitors',
            distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisRequest.SerializeToString,
            distributed__agent__contracts_dot_competitor_dot_v1_dot_competitor__pb2.CompetitorAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
